# Generated by Django 5.1.3 on 2024-12-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_question_subject_mockexam_mockexamquestion_and_more'),
        ('datacollector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.AlterField(
            model_name='mockexamquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollector.pastquestion'),
        ),
        migrations.AlterField(
            model_name='mockexam',
            name='subjects',
            field=models.ManyToManyField(to='datacollector.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
