# Generated by Django 5.1.3 on 2024-12-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email'),
        ('accounts', '0007_remove_question_subject_and_more'),
    ]

    operations = [
    ]
