# Generated by Django 5.1.3 on 2025-01-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexamquestion',
            name='user_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
