# Generated by Django 5.1.3 on 2025-01-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastquestion',
            name='correct_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
