# Generated by Django 5.1.3 on 2025-01-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0003_alter_pastquestion_correct_option_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtopicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='datacollector.subtopic')),
            ],
        ),
        migrations.DeleteModel(
            name='TopicContent',
        ),
    ]
